"""
Script to train initial models on historical seed data
"""
import os
import sys
import json

SERVICE_ROOT = os.path.dirname(os.path.abspath(__file__))
if SERVICE_ROOT not in sys.path:
    sys.path.insert(0, SERVICE_ROOT)

from training.trainer import train_and_compare_models

# Baseline seed records matching repository historical outcomes
SEED_OUTCOMES = [
    {
        "id": "out-13",
        "recommendationId": "rec-13",
        "recommendedActivity": "45-Min Heavy Gym Strength",
        "category": "functional_strength",
        "durationMinutes": 45,
        "intensity": "high",
        "environment": "gym",
        "sleep_hours": 5.5,
        "sleep_quality": 4,
        "energy_level": 4,
        "fatigue_level": 8,
        "stress_level": 7,
        "soreness_level": 6,
        "available_minutes": 50,
        "recommended_time": "evening",
        "day_of_week": "Friday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 58,
        "goal_priority_numeric": 1,
        "outcomeStatus": "skipped",
        "actualDurationMinutes": 0,
        "reasonForSkipOrPartial": "too_tired"
    },
    {
        "id": "out-12",
        "recommendationId": "rec-12",
        "recommendedActivity": "20-Min Home Core & Bands",
        "category": "functional_strength",
        "durationMinutes": 20,
        "intensity": "low",
        "environment": "home",
        "sleep_hours": 6.0,
        "sleep_quality": 5,
        "energy_level": 5,
        "fatigue_level": 6,
        "stress_level": 5,
        "soreness_level": 4,
        "available_minutes": 25,
        "recommended_time": "morning",
        "day_of_week": "Thursday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 64,
        "goal_priority_numeric": 2,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 22
    },
    {
        "id": "out-11",
        "recommendationId": "rec-11",
        "recommendedActivity": "25-Min Dumbbell Circuit",
        "category": "functional_strength",
        "durationMinutes": 25,
        "intensity": "moderate",
        "environment": "home",
        "sleep_hours": 7.5,
        "sleep_quality": 8,
        "energy_level": 8,
        "fatigue_level": 3,
        "stress_level": 3,
        "soreness_level": 2,
        "available_minutes": 35,
        "recommended_time": "morning",
        "day_of_week": "Wednesday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 70,
        "goal_priority_numeric": 1,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 26
    },
    {
        "id": "out-10",
        "recommendationId": "rec-10",
        "recommendedActivity": "40-Min Outdoor Intervals",
        "category": "hiit",
        "durationMinutes": 40,
        "intensity": "high",
        "environment": "outdoor",
        "sleep_hours": 6.2,
        "sleep_quality": 6,
        "energy_level": 5,
        "fatigue_level": 6,
        "stress_level": 6,
        "soreness_level": 4,
        "available_minutes": 45,
        "recommended_time": "afternoon",
        "day_of_week": "Tuesday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 66,
        "goal_priority_numeric": 1,
        "outcomeStatus": "partially_completed",
        "actualDurationMinutes": 20,
        "reasonForSkipOrPartial": "no_time"
    },
    {
        "id": "out-09",
        "recommendationId": "rec-09",
        "recommendedActivity": "20-Min Guided Mobility & Foam Roll",
        "category": "mobility_recovery",
        "durationMinutes": 20,
        "intensity": "low",
        "environment": "home",
        "sleep_hours": 5.2,
        "sleep_quality": 4,
        "energy_level": 4,
        "fatigue_level": 7,
        "stress_level": 8,
        "soreness_level": 7,
        "available_minutes": 30,
        "recommended_time": "evening",
        "day_of_week": "Monday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 62,
        "goal_priority_numeric": 3,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 20
    },
    {
        "id": "out-08",
        "recommendationId": "rec-08",
        "recommendedActivity": "50-Min Gym Leg Session",
        "category": "functional_strength",
        "durationMinutes": 50,
        "intensity": "high",
        "environment": "gym",
        "sleep_hours": 6.0,
        "sleep_quality": 5,
        "energy_level": 4,
        "fatigue_level": 8,
        "stress_level": 6,
        "soreness_level": 5,
        "available_minutes": 40,
        "recommended_time": "afternoon",
        "day_of_week": "Sunday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 59,
        "goal_priority_numeric": 2,
        "outcomeStatus": "skipped",
        "actualDurationMinutes": 0,
        "reasonForSkipOrPartial": "schedule_changed"
    },
    {
        "id": "out-07",
        "recommendationId": "rec-07",
        "recommendedActivity": "25-Min Home Dumbbell Strength",
        "category": "functional_strength",
        "durationMinutes": 25,
        "intensity": "moderate",
        "environment": "home",
        "sleep_hours": 7.0,
        "sleep_quality": 7,
        "energy_level": 7,
        "fatigue_level": 4,
        "stress_level": 4,
        "soreness_level": 3,
        "available_minutes": 35,
        "recommended_time": "morning",
        "day_of_week": "Saturday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 68,
        "goal_priority_numeric": 1,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 25
    },
    {
        "id": "out-06",
        "recommendationId": "rec-06",
        "recommendedActivity": "35-Min Aerobic Zone 2 Run",
        "category": "aerobic_cardio",
        "durationMinutes": 35,
        "intensity": "moderate",
        "environment": "outdoor",
        "sleep_hours": 7.4,
        "sleep_quality": 8,
        "energy_level": 8,
        "fatigue_level": 3,
        "stress_level": 3,
        "soreness_level": 2,
        "available_minutes": 50,
        "recommended_time": "morning",
        "day_of_week": "Friday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 72,
        "goal_priority_numeric": 1,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 36
    },
    {
        "id": "out-05",
        "recommendationId": "rec-05",
        "recommendedActivity": "45-Min Heavy Gym Strength",
        "category": "functional_strength",
        "durationMinutes": 45,
        "intensity": "high",
        "environment": "gym",
        "sleep_hours": 5.8,
        "sleep_quality": 4,
        "energy_level": 4,
        "fatigue_level": 7,
        "stress_level": 6,
        "soreness_level": 5,
        "available_minutes": 45,
        "recommended_time": "afternoon",
        "day_of_week": "Thursday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 60,
        "goal_priority_numeric": 2,
        "outcomeStatus": "skipped",
        "actualDurationMinutes": 0,
        "reasonForSkipOrPartial": "too_tired"
    },
    {
        "id": "out-04",
        "recommendationId": "rec-04",
        "recommendedActivity": "30-Min High-Rep Dumbbell Circuit",
        "category": "functional_strength",
        "durationMinutes": 30,
        "intensity": "moderate",
        "environment": "home",
        "sleep_hours": 6.5,
        "sleep_quality": 6,
        "energy_level": 6,
        "fatigue_level": 5,
        "stress_level": 5,
        "soreness_level": 6,
        "available_minutes": 40,
        "recommended_time": "morning",
        "day_of_week": "Wednesday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 67,
        "goal_priority_numeric": 1,
        "outcomeStatus": "partially_completed",
        "actualDurationMinutes": 18,
        "reasonForSkipOrPartial": "muscle_soreness"
    },
    {
        "id": "out-03",
        "recommendationId": "rec-03",
        "recommendedActivity": "30-Min Cardio Intervals",
        "category": "hiit",
        "durationMinutes": 30,
        "intensity": "high",
        "environment": "home",
        "sleep_hours": 7.2,
        "sleep_quality": 7,
        "energy_level": 7,
        "fatigue_level": 4,
        "stress_level": 4,
        "soreness_level": 3,
        "available_minutes": 40,
        "recommended_time": "morning",
        "day_of_week": "Tuesday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 71,
        "goal_priority_numeric": 1,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 30
    },
    {
        "id": "out-02",
        "recommendationId": "rec-02",
        "recommendedActivity": "20-Min Yoga & Thoracic Flow",
        "category": "mobility_recovery",
        "durationMinutes": 20,
        "intensity": "low",
        "environment": "home",
        "sleep_hours": 6.8,
        "sleep_quality": 7,
        "energy_level": 6,
        "fatigue_level": 5,
        "stress_level": 5,
        "soreness_level": 4,
        "available_minutes": 30,
        "recommended_time": "morning",
        "day_of_week": "Monday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 73,
        "goal_priority_numeric": 3,
        "outcomeStatus": "completed",
        "actualDurationMinutes": 20
    },
    {
        "id": "out-01",
        "recommendationId": "rec-01",
        "recommendedActivity": "45-Min Outdoor Tempo Run",
        "category": "aerobic_cardio",
        "durationMinutes": 45,
        "intensity": "high",
        "environment": "outdoor",
        "sleep_hours": 6.2,
        "sleep_quality": 6,
        "energy_level": 6,
        "fatigue_level": 5,
        "stress_level": 7,
        "soreness_level": 3,
        "available_minutes": 30,
        "recommended_time": "afternoon",
        "day_of_week": "Sunday",
        "preferred_environment": "home",
        "preferred_time": "morning",
        "historical_completion_rate": 69,
        "historical_skip_rate": 23,
        "historical_partial_rate": 8,
        "behavioral_momentum": 65,
        "goal_priority_numeric": 1,
        "outcomeStatus": "skipped",
        "actualDurationMinutes": 0,
        "reasonForSkipOrPartial": "no_time"
    }
]

if __name__ == '__main__':
    print(f"Training models on {len(SEED_OUTCOMES)} demonstration seed records...")
    meta = train_and_compare_models(SEED_OUTCOMES, "Demonstration model trained on seed data")
    print(f"Done! Selected Model: {meta['model_name']}")
    print(f"Selection Rationale: {meta['selection_rationale']}")
    print(f"Metrics: {json.dumps(meta['selected_model_metrics'], indent=2)}")
